---
title: "Cygate group, Barcelona January 26th to 31st 2020"
output: 
  flexdashboard::flex_dashboard:
    logo: logo.png
    theme: sandstone
---


Budget 
===================================== 


```{r echo=FALSE, warning=FALSE, message=FALSE}
tables <- function(x){

x %>% select(1:5) %>% mutate(total = paste("EUR", format(round(total, 2L),nsmall = 2,big.mark = ","))) %>% 
  kable(
   format = "html", escape = F) %>% kable_styling(fixed_thead =   T,bootstrap_options = c("striped","condensed","hover","responsive")) %>%
row_spec(0, bold = T, color = "white", background = "#FFA500")  %>% 
  column_spec(1, width = "8em") %>% 
  column_spec(5,bold = TRUE, width = "12em")}
```


_**Cygate group**_ {data-width=850}
-------------------------------------------

### Budget as of May 29, 2019

<br><br>

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(DT)
library(readxl)
library(lubridate)
library(dplyr)
library(chron)
library(kableExtra)
library(scales)
library(tidyverse)

budget <- read_excel("rooming.xlsx", sheet = "bud") 
budget <- sapply(budget, as.character)
budget[is.na(budget)] <- ""
budget <- data.frame(budget, stringsAsFactors = FALSE)
class(budget$bud_units) <- "numeric"
class(budget$bud_cost) <- "numeric"
class(budget$bud_total) <- "numeric"

names(budget) <- c("date","description","units","unit cost","total","category")


budget[nrow(budget),] <- c("","","<strong>Total</strong>","",sum(budget$total),"")

class(budget$total) <- "numeric"

tables(budget)

```

_**Cygate group**_{data-width=150}
-------------------------------------------

```{r echo=FALSE, message=FALSE, warning=FALSE}

library(dplyr)
library(flexdashboard)

budget <- budget[-nrow(budget),]

bud_transfers <- budget %>% filter(category == "transfer") %>% summarise(total= sum(total)) %>% prettyNum(big.mark = ",")

bud_activity <- budget %>% filter(category == "activity") %>% summarise(total= sum(total))%>% prettyNum(big.mark = ",")

bud_hotel <- budget %>% filter(category == "hotel") %>% summarise(total = sum(total))%>% prettyNum(big.mark = ",")

bud_restaurant <- budget %>% filter(category == "restaurant") %>%  summarise(total = sum(total)) %>% prettyNum(big.mark = ",")

bud_audiovisuals <- budget %>% filter(category == "audiovisuals") %>%  summarise(total = sum(total)) %>% prettyNum(big.mark = ",")

```

<br>

### hotel

```{r echo=FALSE, warning=FALSE, message=FALSE}

valueBox(bud_hotel, 
         icon = "fa-h-square", 
         caption = "Euros in Hotel",
         color = "#fcffc2")
```


### activities

```{r echo=FALSE, warning=FALSE, message=FALSE}

valueBox(bud_activity, 
         icon = "fa-walking", 
         caption = "Euros in activities",
         color = "#b6fcd5")
```


### transfers

```{r echo=FALSE, message=FALSE, warning=FALSE}

valueBox(bud_transfers, icon = "fa-shuttle-van",
         caption = "Euros in transfers",
         color = "#c6e2ff")

```

### restaurants

```{r echo=FALSE, warning=FALSE, message=FALSE}

valueBox(bud_restaurant, 
         icon = "fa-utensils", 
         caption = "Euros in offsite restaurants",
         color = "#fdc9d9")
```


### Audiovisuals

```{r echo=FALSE, warning=FALSE, message=FALSE}

valueBox(bud_audiovisuals, 
         icon = "fa-fast-forward", 
         caption = "Euros in Audiovisuals",
         color = "#b6a3ea")
```


Proforma 
===================================== 


_**Cygate group**_ {data-width=850}
-------------------------------------------

### Budget as of May 29, 2019

<br>

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(DT)
library(readxl)
library(lubridate)
library(dplyr)
library(chron)
library(kableExtra)
library(scales)
library(tidyverse)

proforma <- read_excel("rooming.xlsx", sheet = "prof") 
proforma <- sapply(proforma, as.character)
proforma[is.na(proforma)] <- ""
proforma <- data.frame(proforma, stringsAsFactors = FALSE)
class(proforma$prof_units) <- "numeric"
class(proforma$prof_cost) <- "numeric"
class(proforma$prof_total) <- "numeric"
names(proforma) <- c("date","description","units","unit cost","total","category")


proforma[nrow(proforma),] <- c("","","<strong>Total</strong>","",sum(proforma$total),"")

class(proforma$total) <- "numeric"

tables(proforma)


```

_**Cygate group**_ {data-width=150}
-------------------------------------------

<br><br>


### total proforma

```{r echo=FALSE, warning=FALSE, message=FALSE}

library(dplyr)
library(flexdashboard)

dip <- read_excel("rooming.xlsx", sheet = "dip") 
dip$amount <- as.numeric(dip$amount)
dip_sum <- dip %>% group_by(paid) %>% summarise(sum = sum(amount)) 

total <- sum(dip_sum$sum)

total %>% prettyNum(big.mark = ",") %>% 
valueBox(
         icon = "fa-euro-sign", 
         caption = "Total requested",
         color = "#ffa500")
```


### _**Total paid %**_

```{r echo=FALSE, message=FALSE, warning=FALSE}

paid_dip <- dip_sum$sum[dip_sum$paid == "yes"] 

gauge(round(100*paid_dip/total,0), min = 0, max = 100, symbol = '%', gaugeSectors(colors = "yellow"),label = paste0("Total paid ", paid_dip," "))

```


### _**Summary table %**_

```{r echo=FALSE, message=FALSE, warning=FALSE}

library(formattable)
library(readxl)

dip <- read_excel("rooming.xlsx", sheet = "dip")
dip$paid <- ifelse(dip$paid == "yes",TRUE,FALSE)
formattable(dip, list(paid = formatter("span",
      style = x ~ style(color = ifelse(x, "green", "red")),
      x ~ icontext(ifelse(x, "ok", "remove"), ifelse(x, "Yes", "No")))))
            
```

